<?php

namespace MyNetwork\BackendBundle\Repository;

/**
 * PublicationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationsRepository extends \Doctrine\ORM\EntityRepository
{
}
